制御構文2の課題
zucchi0830/php_exercise01 pull request #5
Opened 2022-07-18 01:12 UTC by zucchi0830

最後の問題で「switch」を使うことがイメージできませんでした。。
ヒントをいただければ🙇‍♂️

2022-07-18 05:40 UTC, kazu-taka requested changes
@zucchi0830 
コメントしたので確認お願いします🙏

2022-07-18 05:40 UTC, kazu-taka commented on 05/if2_5.php
> +];
@zucchi0830 
ここは連想配列にせず、3行目に書いてある配列をそのまま使用して頂いて問題ないです✨

2022-07-18 05:40 UTC, kazu-taka commented on 05/if2_1.php
> +$balance = $poket_money - $fund_raising;
@zucchi0830 
$balanceという変数は追加せずに、$poket_moneyの値を減らすことで残高となるので、$poket_moneyを減らして段坂として表示させるようにしてみて下さい✨
また、募金の処理はここに記述せず、whileの中に記述することで、残金を求める処理が1箇所で行う事が可能です！
(次の課題も同様です)

2022-07-18 05:40 UTC, kazu-taka commented on 05/if2_1.php
> +while ($balance > 0) {
@zucchi0830 
残金が0円より大きいかという判定より、残金が募金額以上の場合、募金を行うという判定でも良いと思います✨
(次の課題も同様です)

2022-07-18 06:44 UTC, kazu-taka approved these changes
@zucchi0830 
コメントしましたが、このままマージしてOKです👍

2022-07-18 06:44 UTC, kazu-taka commented on 05/if2_1.php
> +    $poket_money -= $fund_raising;
@zucchi0830 
2回引き算をしてますが、echoの前に引いてしまって、残金を出力する時に`$poket_money`を使用しても良いです✨
次の課題も同様です！

2022-07-20 12:05 UTC, zucchi0830 commented on 05/if2_1.php
> +    $poket_money -= $fund_raising;
ありがとうございます!修正し、マージします!!

2022-07-20 12:05 UTC, merged