フォームの課題
zucchi0830/php_exercise01 pull request #7
Opened 2022-07-18 05:40 UTC by zucchi0830

ご確認お願いします♨

2022-07-18 06:38 UTC, kazu-taka requested changes
@zucchi0830 
コメントしたので確認お願いします✨

2022-07-18 06:38 UTC, kazu-taka commented on 06/form_1.php
> +        <?= htmlspecialchars($msg, ENT_QUOTES, 'UTF-8') ?>
@zucchi0830 
$ageが未入力のときは、上記のコードを実行する必要がないので、修正お願いします🙏

2022-07-18 06:38 UTC, kazu-taka commented on 06/form_5.php
> +    }
@zucchi0830 
ここのelseifはどこのif文にも紐付いていないので、修正お願いします🙏
合計値を求めることはできているので、そのif文のelseで良いと思います✨

2022-07-20 12:20 UTC, zucchi0830 commented
ご確認お願いします。来い!ガッキー!

2022-07-20 21:35 UTC, kazu-taka commented
@zucchi0830 
問題ないのでマージしてOKです😊
別の<a href="https://ja.wikipedia.org/wiki/%E6%96%B0%E5%9E%A3%E9%9A%86">ガッキー</a>です笑✨

![LGTM](https://image.lgtmoon.dev/174556)

2022-07-20 23:56 UTC, merged